version: 2
updates:
  - directory: "/server"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    assignees:
      - "Timeraa"
      - "TheDropX"
    commit-message:
      prefix: "🔼"
      prefix-development: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "daily"
    assignees:
      - "Timeraa"
      - "TheDropX"
    commit-message:
      prefix: "🔼"
      prefix-development: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
